### ISSUE TITLE
Missing PyNaCl and FFmpeg (Windows)

### ISSUE THREAD

**Issue by surf472** [LukaRaspudic/Palpatunes-Discord-Music-Bot#1]
Works perfectly on Windows once those two dependencies are accounted for. 
Fixes (Sorry I don't know how pull requests work): Add pip install pynacl to requirements
Download FFmpeg (this is different for linux users)
Implement ffmpeg location in code (again this will be different for linux users)

Add this somewhere in the bot: 

.# Set the path to your FFmpeg executable (copy / paste to FFmpeg.exe path on windows)
FFMPEG_PATH = r"C:\Users\osrst\Downloads\....bin\ffmpeg.exe" (replace with your own path)

Implement the path into play_next logic

async def play_next(guild_id, voice_channel):
    if queues.get(guild_id):
        url = queues[guild_id].popleft()

        ydl_opts = {
            'format': 'bestaudio',
            'outtmpl': 'downloads/%(title)s.%(ext)s',
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            audio_url = info.get('url')

            if audio_url:
                voice_channel.play(discord.FFmpegPCMAudio(audio_url, executable=FFMPEG_PATH), after=lambda e: print('done', e))
                await bot.get_channel(voice_channel.channel.id).send(f'Now playing: {info["title"]}')

                # Check if there are more songs in the queue
                if queues.get(guild_id):
                    await play_next(guild_id, voice_channel)
            else:
                await bot.get_channel(voice_channel.channel.id).send(f'Error: No audio stream found for {info["title"]}')

@bot.event
async def on_voice_state_update(member, before, after):
    if not member.bot and after.channel is None:
        voice_channel = discord.utils.get(bot.voice_clients, guild=member.guild)
        if voice_channel and not voice_channel.is_playing():
            await play_next(member.guild.id, voice_channel)
#End of music player code

Thanks again!

**Comment by LukaRaspudic** [comment]
Thanks for the info. I actually run this in linux so it all works perfectly for me. Going to test it out on other systems with the changes to make it so it runs for other systems. Still updating the README but I believe I have a work around for the FFmpeg file path. The command 'sudo apt install ffmpeg' fixes the filepath problem for me so it is not required.
